import Head from 'next/head';

import NavBar from '../components/nav/navbar';
import Banner from '../components/banner/banner';
import SectionCards from '../components/card/section-cards';

import styles from '../styles/Home.module.css';

import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from '../lib/videos';

export async function getServerSideProps(context) {
  const token = context.req ? context.req?.cookies.token : null;
  console.log({ token });
  const userId = 'did:ethr:0xB11F29037A7b7062179A3F186D2e11203Ba1dcE8';

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);
  console.log({ watchItAgainVideos });
  const disneyVideos = await getVideos('disney trailer');
  const documentaryVideos = await getVideos('friends clip');
  const ghibliVideos = await getVideos('ghibli trailer');
  const popularVideos = await getPopularVideos();

  return {
    props: {
      disneyVideos,
      documentaryVideos,
      ghibliVideos,
      popularVideos,
      watchItAgainVideos,
    },
  };
}

export default function Home({
  disneyVideos,
  documentaryVideos,
  ghibliVideos,
  popularVideos,
  watchItAgainVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.main}>
        <NavBar />
        <Banner
          videoId='l1uINfUshjc'
          title='SPY × FAMILY'
          subtitle='A spy adopts a cute child.'
          imgUrl='/static/spy-x-family.jpg'
        />
        <div className={styles.sectionWrapper}>
          <SectionCards
            title='Watch it again'
            videos={watchItAgainVideos}
            size='small'
          />
          <SectionCards title='Disney' videos={disneyVideos} size='large' />
          <SectionCards
            title='Ghibli Studio'
            videos={ghibliVideos}
            size='small'
          />
          <SectionCards
            title='Your Favorite Series'
            videos={documentaryVideos}
            size='medium'
          />
          <SectionCards title='Popular' videos={popularVideos} size='small' />
        </div>
      </div>
    </div>
  );
}
