import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/nav/navbar';
import Banner from '../components/banner/banner';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username='bibo@bibibo.com' />
      <Banner
        title='Clifford the red dog'
        subtitle='a very cute dog'
        imgUrl='/static/clifford.webp'
      />
      {/*
      <Card /> */}
    </div>
  );
}
